package treenikirja.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import treenikirja.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2022.05.04 20:31:18 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class PaivamaaraTest {
	
	 @Test
	 public void testLuoTreeni() {
		 Paivamaara paivamaara1 = new Paivamaara(), paivamaara2 = new Paivamaara();
		 paivamaara1.luoTreeni();
		 paivamaara2.luoTreeni();
		 assertEquals("From: Paivamaara line: 1", 1, paivamaara2.getPaivamaaranNro());
	 }
	 
	 
	 @Test
	 public void testToString() {
		 Paivamaara paivamaara1 = new Paivamaara();
		 paivamaara1.luoTreeni();
		 assertEquals("From: Paivamaara line: 1", paivamaara1.paivamaaraNro + "|" + paivamaara1.paivamaara + "|null|null|null|null|null|null|null|", paivamaara1.toString());
	 }
	 
	 
	 @Test
	 public void testParse() {
		 Paivamaara paivamaara = new Paivamaara();
		 paivamaara.luoTreeni();
		 int n = paivamaara.getPaivamaaranNro(); 
		 paivamaara.parse(""+(n));
		 paivamaara.luoTreeni();
		 assertEquals("From: Paivamaara line: 2", n+1, paivamaara.getPaivamaaranNro()); 
	 }
	 
	 
	 
}