package treenikirja.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;

import java.io.File;
import java.io.FileNotFoundException;

import org.junit.*;
import treenikirja.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2022.05.04 19:29:12 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class PaivamaaratTest {
	
	  @Test
	  public void testLisaa(){
		  Paivamaarat paivamaarat = new Paivamaarat(); 
		  Paivamaara paivamaara1 = new Paivamaara(), paivamaara2 = new Paivamaara(); 
		  assertEquals("From: Paivamaarat line: 0", 0, paivamaarat.getLkm()); 
		  paivamaarat.lisaa( paivamaara1); assertEquals("From: Jasenet line: 1", 1, paivamaarat.getLkm()); 
		  paivamaarat.lisaa(paivamaara2); assertEquals("From: Jasenet line: 2", 2, paivamaarat.getLkm()); 
	  }
	  
	  @Test
	  public void testPoista() {
		  Paivamaarat paivamaarat = new Paivamaarat(); 
		  Paivamaara paivamaara1 = new Paivamaara(), paivamaara2 = new Paivamaara(), paivamaara3 = new Paivamaara();
		  assertEquals("From: Paivamaarat line: 0", 0, paivamaarat.getLkm());
		  paivamaarat.lisaa(paivamaara1); paivamaarat.lisaa(paivamaara2); paivamaarat.lisaa(paivamaara3);
		  paivamaarat.poista(paivamaara1);
		  assertEquals("From: Paivamaarat line: 0", null , paivamaarat.anna(1));
	  }
	  
	  @Test
	  public void testLueTiedostosta() throws SailoException, FileNotFoundException {
		  Paivamaarat paivamaarat = new Paivamaarat(); 
		  Paivamaara paivamaara1 = new Paivamaara(), paivamaara2 = new Paivamaara(); 
		  paivamaara1.luoTreeni(); 
		  paivamaara2.luoTreeni(); 
		  String hakemisto = "testi"; 
		  String tiedNimi = hakemisto+"/paivamaarat"; 
		  File ftied = new File(tiedNimi+".dat"); 
		  File dir = new File(hakemisto); 
		  dir.mkdir(); 
		  ftied.delete(); 
		  paivamaarat.lisaa(paivamaara1); 
		  paivamaarat.lisaa(paivamaara2); 
		  paivamaarat.tallenna();
		  assertEquals("From: Tyypit line: 2", 2, paivamaarat.getLkm());
	  }
	  
}