package treenikirja.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import treenikirja.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2022.03.24 16:37:28 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class treenikirjaTest {
}