package treenikirja.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import static org.junit.jupiter.api.Assertions.assertEquals;

import org.junit.*;
import treenikirja.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2022.03.24 16:37:28 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class treenikirjaTest {
	
	
	 @Test
	 public void testKysy() {
		 treenikirja treenikirja = new treenikirja();
		 assertEquals("From: Treenikirja line: 2", false, treenikirja.kysy("T‰t‰EiOleOlemassa"));
	 }
	 
	 
	 @Test
	 public void testPoista() {
		 treenikirja treenikirja = new treenikirja();
		 Paivamaara paivamaara1 = new Paivamaara(); paivamaara1.luoTreeni();
		 Paivamaara paivamaara2 = new Paivamaara(); paivamaara2.luoTreeni();
		 assertEquals("From: Paivamaarat line: 0", 0, treenikirja.getPaivamaarat());
		 treenikirja.lisaa(paivamaara1); treenikirja.lisaa(paivamaara2);
		 treenikirja.poista(paivamaara1);
		 assertEquals("From: Paivamaarat line: 0", null , treenikirja.annaPaivamaara(1));
	 }
	
	
}