package treenikirja.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;

import java.io.File;
import java.io.FileNotFoundException;
import java.io.IOException;

import org.junit.*;
import treenikirja.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2022.05.04 19:37:57 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class TyypitTest {
	
	 
	 @Test
	 public void testAlusta() {
		 Tyypit tyypit = new Tyypit();
		 tyypit.alusta();
		 assertEquals("From: Tyypit line: 8", 8, tyypit.getLkm());
	 }
	 
	 
	 @Test
	 public void testLisaa() {
		 Tyypit tyypit = new Tyypit();
		 Tyyppi tyyppi1 = new Tyyppi(); Tyyppi tyyppi2 = new Tyyppi();
		 tyyppi1.alusta();
		 tyyppi2.alusta();
		 tyypit.lisaa(tyyppi1);
		 tyypit.lisaa(tyyppi2);
		 assertEquals("From: Tyypit line: 2", 2, tyypit.getLkm());
	 }
	 
	 
	  @Test
	  public void testLueTiedostosta() throws SailoException, IOException {
		  Tyypit tyypit = new Tyypit(); 
		  Tyyppi tyyppi1 = new Tyyppi(); Tyyppi tyyppi2 = new Tyyppi();
		  tyyppi1.alusta();
		  tyyppi2.alusta();
		  String hakemisto = "testi"; 
		  String tiedNimi = hakemisto+"/tyypit"; 
		  File ftied = new File(tiedNimi+".dat"); 
		  File dir = new File(hakemisto); 
		  dir.mkdir(); 
		  tyypit.lisaa(tyyppi1); 
		  tyypit.lisaa(tyyppi2); 
		  tyypit.tallenna(); 
		  tyypit.lueTiedostosta(tiedNimi); 
		  assertEquals("From: Tyypit line: 2", 3, tyypit.getLkm());
	  }
	  
	  
}