package treenikirja.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import treenikirja.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2022.05.04 20:52:48 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class TyyppiTest {
	
	 @Test
	 public void testToString() {
		 Tyyppi tyyppi = new Tyyppi();
		 tyyppi.alusta();
		 assertEquals("From: Paivamaara line: 1", tyyppi.id      + "|" + tyyppi.tyyppi + "|" + tyyppi.kestoH   + "|" + tyyppi.kestoMin + "|" + 
				 								  tyyppi.kalorit + "|" + tyyppi.matka  + "|" + tyyppi.askeleet + "|" + tyyppi.syke     + "|" , 
				 								  tyyppi.toString());
	 }
	 
	 
	 @Test
	 public void testParse() {
		 Tyyppi tyyppi = new Tyyppi();
		 tyyppi.alusta();
		 assertEquals("From: Paivamaara line: 2", tyyppi.id, tyyppi.id); 
	 }
}